source "https://rubygems.org"

ruby "4.0.3"

gem "bcrypt", "~> 3.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "rails", "~> 8.0"

group :development, :test do
  gem "debug", "~> 1.10"
  gem "rspec-rails", "~> 7.1"
  gem "rubocop-rails-omakase", "~> 1.0", require: false
end
